language: python
dist: focal

# This stops the entire job from running if it's a PR
if: type != pull_request

python:
  - "3.10"
  - "3.11"
  - "3.12"

install:
  - python -m pip install --upgrade pip
  - python -m pip install poetry
  - poetry install

script:
  - poetry run pytest
